line-length = 80

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]

exclude = [
  "task_manager/task_manager/settings.py",
  "task_manager/*/migrations/*.py",
  "task_manager/users/urls.py"
]