# Generated by Django 6.0.6 on 2026-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_remove_label_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(error_messages={'unique': 'already exists'}, max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
