# Generated by Django 6.0.6 on 2026-06-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_labels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(error_messages={'unique': 'already exists'}, max_length=200, unique=True),
        ),
    ]
