# Generated by Django 6.0.6 on 2026-06-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
    ]
