# Generated by Django 6.0.6 on 2026-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(error_messages={'unique': 'already exists'}, max_length=200, unique=True),
        ),
    ]
