# Generated by Django 6.0.6 on 2026-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_remove_label_tasks'),
        ('tasks', '0003_alter_task_author_alter_task_executor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='labels.label', verbose_name='Label'),
        ),
    ]
