name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run migrations
        env:
          DJANGO_DB_HOST: localhost
        run: |
          make migrate
          make apply migrations
      - name: Run tests
        run: |
          make test
      - name: Run linter
        run: |
          make lint
          
